const resources = {
    "Water Fountain": "Water fountains provide free and accessible hydration, ensuring people stay healthy and refreshed throughout the day. They promote environmental sustainability by reducing the need for single-use plastic bottles. Additionally, they support public health by encouraging regular water intake, which is essential for overall well-being.",
    "Libraries": "Libraries offer free access to books, knowledge, and resources, promoting lifelong learning and literacy. They serve as community hubs where people can study, collaborate, and attend educational programs. Beyond books, libraries provide internet access and quiet spaces, making them essential for education and personal growth.",
    "Bathrooms": "Bathrooms are essential for hygiene, sanitation, and overall public health, ensuring people have a clean and private space to relieve themselves. They promote dignity and accessibility, especially in public spaces, workplaces, and schools. Proper restroom facilities also help prevent the spread of disease and maintain a healthy environment for everyone.",
    "Hospitals": "Hospitals are vital for providing emergency medical care, surgeries, and ongoing treatments that help save lives and improve overall health. They offer specialized care through doctors, nurses, and advanced medical technology to diagnose and treat various conditions. Beyond emergencies, hospitals also focus on preventive care, rehabilitation, and medical research to enhance long-term well-being.",
    "Charging Stations": "Charging stations are essential for supporting electric vehicles by providing convenient access to power, reducing reliance on gasoline. They contribute to a cleaner environment by encouraging the adoption of sustainable transportation and lowering carbon emissions. As electric vehicle usage grows, expanding the network of charging stations ensures accessibility and promotes the transition to greener mobility.",
    "Bus Stations": "Bus stops play a crucial role in public transportation by providing designated locations for passengers to board and exit buses safely. They enhance urban mobility by connecting people to workplaces, schools, and essential services, reducing traffic congestion and pollution. Well-placed and well-maintained bus stops improve accessibility, making public transit a more efficient and convenient option for communities.",
};

export default resources;